In [1]:
import numpy as np 

In [2]:
simple_list=[6,7,9]

In [3]:
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [22]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(3,5)

array([[0.35484383, 0.63281884, 0.09416515, 0.51791335, 0.63188105],
       [0.91975115, 0.21067478, 0.39257401, 0.3935792 , 0.64432257],
       [0.00413955, 0.32676469, 0.13247528, 0.94621987, 0.37869059]])

In [26]:
arr=np.random.randn(2,4)
arr

array([[ 0.86690428, -0.31509906,  0.24491766, -1.46649041],
       [-0.40966633,  0.40873237,  0.71125753,  0.28813546]])

In [28]:
np.random.randint(2,100)

62

In [29]:
np.random.randint(20,56,100)

array([50, 25, 50, 20, 46, 42, 54, 46, 32, 30, 33, 27, 35, 31, 53, 29, 53,
       54, 50, 54, 27, 33, 45, 37, 33, 45, 24, 34, 27, 28, 30, 39, 29, 41,
       39, 49, 36, 31, 41, 33, 31, 29, 42, 20, 26, 44, 23, 46, 26, 31, 53,
       36, 41, 49, 33, 53, 22, 34, 23, 48, 33, 39, 29, 51, 33, 35, 39, 53,
       25, 21, 49, 22, 32, 46, 28, 31, 28, 41, 29, 22, 40, 52, 44, 53, 38,
       50, 30, 36, 23, 45, 29, 42, 52, 31, 31, 45, 50, 47, 34, 50])

In [30]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
rand_array=np.random.randint(0,100,20)
rand_array

array([48,  5, 54, 99, 20, 74, 22, 79,  3,  9, 28, 37, 68, 22, 10, 80, 91,
       96, 40,  6])

In [32]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [37]:
rand_array.max()

99

In [39]:
rand_array.argmax()

3

In [44]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a=np.random.rand(2,3)
a

array([[0.97284687, 0.88360497, 0.03606029],
       [0.26949273, 0.38143492, 0.71145326]])

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
sample_array[0]


10

In [50]:
sample_array[2:5]

array([12, 13, 14])

In [52]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [56]:
sample_array=np.arange(10,21)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [62]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [63]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [64]:
import numpy as np

In [65]:
sample_matrix=np.array([[50,21,31,1],[20,32,31,45],[2,4,8,90]])
sample_matrix

array([[50, 21, 31,  1],
       [20, 32, 31, 45],
       [ 2,  4,  8, 90]])

In [66]:
sample_matrix[1,2]

31

In [69]:
sample_matrix[2,:]

array([ 2,  4,  8, 90])

In [70]:
sample_matrix[2]

array([ 2,  4,  8, 90])

In [71]:
sample_matrix[:,(3,2)]

array([[ 1, 31],
       [45, 31],
       [90,  8]])